version: '3.8'

services:
  # --------- PostgreSQL xidməti ----------
  postgres:
    image: postgres:15
    container_name: postgres-con
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --------- Java tətbiq xidməti ----------
  app:
    build: .
    container_name: postgres-con
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      # Spring Boot application.yml içində override üçün
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: on-failure

volumes:
  postgres_data:
